# .github/workflows/slack-ping-dev.yml
name: Slack ping test (canal #dev)

on: workflow_dispatch          # lo lanzas manualmente desde Actions

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Send ping to #dev
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}   # URL del incoming-webhook
          webhook-type: incoming-webhook
          payload: |
            {
              "text": ":wave: *Ping exitoso* desde GitHub Actions al canal #dev"
            }
